# -*- coding: utf-8 -*-
HOLIDAYS_Q3 = {
    # ───────────────── ИЮЛЬ ─────────────────
    (7, 1):  [("День ветеранов органов внутренних дел", "pro", "police law honor"), ("Международный день архитектуры", "international", "architecture building design")],
    (7, 2):  [("Международный день спортивного журналиста", "pro", "sport journalism camera")],
    (7, 3):  [("День ГИБДД", "pro", "police road traffic")],
    (7, 4):  [("День Republic of independence (мировые культуры)", "international", "celebration colorful fireworks")],
    (7, 5):  [("Международный день кооперативов", "international", "business teamwork hands")],
    (7, 6):  [("День Ивана Купалы", "fun", "summer flowers river tradition")],
    (7, 7):  [("Рождество Иоанна Предтечи", "church", "orthodox cross summer")],
    (7, 8):  [("День семьи, любви и верности", "state", "family love romantic flowers")],
    (7, 9):  [("День российской почты", "pro", "mail letters delivery")],
    (7, 10): [("День российской почты (альт.)", "pro", "mail letters delivery"), ("День победы русской армии при Полтаве", "state", "memorial flag history")],
    (7, 11): [("Всемирный день шоколада", "international", "chocolate sweet dessert")],
    (7, 12): [("День апостолов Петра и Павла", "church", "orthodox cross history")],
    (7, 13): [("Всемирный день фотографии (альт.)", "fun", "photography camera art")],
    (7, 14): [("День российской почты (рег.)", "pro", "mail letters delivery")],
    (7, 15): [("День изобретения водки", "fun", "vintage retro nostalgia")],
    (7, 16): [("Всемирный день змеи", "fun", "snake nature wildlife")],
    (7, 17): [("Международный день эмодзи", "fun", "emoji colorful fun")],
    (7, 18): [("Всемирный день шахмат (альт)", "fun", "chess board game")],
    (7, 19): [("День металлурга", "pro", "industry factory metal")],
    (7, 20): [("Международный день шахмат", "international", "chess board game")],
    (7, 21): [("День металлурга (рег.)", "pro", "industry factory")],
    (7, 22): [("Всемирный день мозга", "fun", "brain science health")],
    (7, 23): [("День системного администратора", "pro", "computer technology desk")],
    (7, 24): [("День физкультурника (альт.)", "fun", "sport fitness outdoor")],
    (7, 25): [("День сотрудника органов следствия", "pro", "law order justice")],
    (7, 26): [("День парашютиста", "fun", "sky parachute adventure")],
    (7, 27): [("День Военно-морского флота", "state", "navy ocean ship flag")],
    (7, 28): [("День Крещения Руси", "church", "orthodox church cross history")],
    (7, 29): [("Международный день тигра", "international", "tiger wildlife nature")],
    (7, 30): [("Международный день дружбы", "international", "friends together happy")],
    (7, 31): [("День Военно-морского флота (рег.)", "pro", "navy ocean ship")],

    # ───────────────── АВГУСТ ─────────────────
    (8, 1):  [("День Гранёного стакана", "fun", "vintage glass nostalgia retro"), ("День памяти русских воинов в Первой мировой войне", "state", "memorial flag history")],
    (8, 2):  [("День Воздушно-десантных войск", "pro", "military parachute flag")],
    (8, 3):  [("День арбуза", "fun", "watermelon summer fruit")],
    (8, 4):  [("Международный день пива", "international", "beer celebration summer")],
    (8, 5):  [("Международный день светофора", "fun", "traffic light city")],
    (8, 6):  [("День Хиросимы — день памяти", "international", "peace candles memorial")],
    (8, 7):  [("День физкультурника", "fun", "sport fitness outdoor")],
    (8, 8):  [("Международный день альпинизма", "international", "mountains hiking adventure")],
    (8, 9):  [("Международный день коренных народов", "international", "culture tradition nature")],
    (8, 10): [("День строителя", "pro", "construction building architecture")],
    (8, 11): [("День строителя (альт.)", "pro", "construction building")],
    (8, 12): [("День Военно-воздушных сил", "state", "aviation military sky")],
    (8, 13): [("День физкультурника (рег.)", "fun", "sport fitness outdoor")],
    (8, 14): [("Медовый Спас", "church", "honey harvest orthodox")],
    (8, 15): [("День археолога", "fun", "history ancient artifacts")],
    (8, 16): [("День физкультурника (доп.)", "fun", "sport fitness outdoor")],
    (8, 17): [("День HR-менеджера", "pro", "office business people")],
    (8, 18): [("День Тихоокеанского флота", "pro", "navy ocean ship")],
    (8, 19): [("Яблочный Спас (Преображение Господне)", "church", "apples harvest orthodox autumn")],
    (8, 20): [("День шахтёра (третья субота, иногда эта дата)", "pro", "mining industry coal")],
    (8, 21): [("День риэлтора", "pro", "real estate home keys")],
    (8, 22): [("День Государственного флага России", "state", "russia flag blue sky white")],
    (8, 23): [("День разгрома советскими войсками немецко-фашистских войск в Курской битве", "state", "memorial flame flag")],
    (8, 24): [("Международный день, посвящённый солидарности журналистов", "international", "journalism press camera")],
    (8, 25): [("День шахтёра (альт.)", "pro", "mining industry coal")],
    (8, 26): [("День образования российского нотариата", "pro", "law documents office")],
    (8, 27): [("День российского кино", "pro", "cinema film movie theater")],
    (8, 28): [("Успение Пресвятой Богородицы", "church", "orthodox church candles")],
    (8, 29): [("День шахтёра (рег.)", "pro", "mining industry coal")],
    (8, 30): [("День ветеринарного работника", "pro", "veterinary animals care")],
    (8, 31): [("День ветеринарного работника (альт.)", "pro", "veterinary animals pets")],

    # ───────────────── СЕНТЯБРЬ ─────────────────
    (9, 1):  [("День знаний", "state", "school education books backpack")],
    (9, 2):  [("День российской гвардии", "pro", "military flag honor")],
    (9, 3):  [("День солидарности в борьбе с терроризмом", "state", "memorial candles peace")],
    (9, 4):  [("День специалиста по ядерному обеспечению", "pro", "science technology nuclear")],
    (9, 5):  [("Международный день благотворительности", "international", "charity helping hands kindness")],
    (9, 6):  [("День работников нефтяной и газовой промышленности", "pro", "industry energy factory")],
    (9, 7):  [("День Бородинского сражения", "state", "memorial flag history")],
    (9, 8):  [("Международный день грамотности", "international", "books reading education")],
    (9, 9):  [("Международный день красоты", "international", "beauty flowers cosmetics")],
    (9, 10): [("Всемирный день предотвращения самоубийств", "international", "support hands care")],
    (9, 11): [("День памяти жертв терроризма", "international", "memorial candles peace")],
    (9, 12): [("День программиста (в невисокосный год)", "pro", "computer code technology")],
    (9, 13): [("День парикмахера", "pro", "beauty salon style")],
    (9, 14): [("Всемирный день первой помощи", "international", "health care medical cross")],
    (9, 15): [("День работников леса", "pro", "forest nature trees")],
    (9, 16): [("Международный день охраны озонового слоя", "international", "earth planet sky")],
    (9, 17): [("День работников леса (рег.)", "pro", "forest nature trees")],
    (9, 18): [("День оружейника", "pro", "metal industry craft")],
    (9, 19): [("День оружейника (рег.)", "pro", "industry craft")],
    (9, 20): [("День здоровья полости рта", "fun", "dental health smile")],
    (9, 21): [("Международный день мира", "international", "peace doves white nature")],
    (9, 22): [("День осеннего равноденствия", "fun", "autumn equinox leaves nature")],
    (9, 23): [("Всемирный день жестовых языков", "international", "communication hands culture")],
    (9, 24): [("Всемирный день моря", "fun", "ocean sea waves blue")],
    (9, 25): [("День машиностроителя", "pro", "engineering factory industry")],
    (9, 26): [("Европейский день языков", "international", "books language culture")],
    (9, 27): [("Всемирный день туризма", "international", "travel adventure landscape")],
    (9, 28): [("Всемирный день моря (альт.)", "fun", "ocean sea waves")],
    (9, 29): [("Всемирный день сердца", "international", "health heart care")],
    (9, 30): [("День интернета в России", "fun", "internet technology connection")],
}
