# -*- coding: utf-8 -*-
"""
Полный календарь праздников на каждый день года.
Формат: (месяц, день): [(название, тип, тема для картинки), ...]
Типы: state, church, pro, fun, international
Если несколько праздников на дату — все идут в список, бот выбирает случайно.
"""

HOLIDAYS_Q1 = {
    # ───────────────── ЯНВАРЬ ─────────────────
    (1, 1):  [("Новый год", "state", "new year celebration fireworks snow")],
    (1, 2):  [("День спокойствия", "fun", "calm relax cozy home")],
    (1, 3):  [("День ручного письма", "fun", "handwriting letter vintage pen")],
    (1, 4):  [("День Республики Алтай", "state", "mountains nature altai"), ("Всемирный день азбуки Брайля", "international", "books reading touch")],
    (1, 5):  [("День детского кино", "fun", "cinema children colorful")],
    (1, 6):  [("Сочельник", "church", "christmas eve candles snow stars")],
    (1, 7):  [("Рождество Христово", "church", "christmas orthodox candles snow")],
    (1, 8):  [("День детского кино", "fun", "children cinema colorful"), ("Народный праздник Бабьи каши", "church", "winter tradition family")],
    (1, 9):  [("День российской печати", "pro", "newspaper printing press")],
    (1, 10): [("День заповедников и национальных парков", "fun", "nature reserve forest wildlife")],
    (1, 11): [("Международный день \"Спасибо\"", "international", "gratitude thank you cards")],
    (1, 12): [("День работника прокуратуры", "pro", "law justice building")],
    (1, 13): [("Старый Новый год", "fun", "winter snow candles cozy")],
    (1, 14): [("День Гидрометеослужбы", "pro", "weather sky clouds")],
    (1, 15): [("День образования Республики Крым", "state", "crimea sea landscape")],
    (1, 16): [("День зимующих птиц", "fun", "winter birds snow cute")],
    (1, 17): [("День детских изобретений", "fun", "invention creativity kids colorful")],
    (1, 18): [("День Республики Тыва", "state", "mountains nature siberia")],
    (1, 19): [("Крещение Господне", "church", "epiphany orthodox water winter")],
    (1, 20): [("День пингвина", "fun", "penguin cute snow")],
    (1, 21): [("День инженерных войск", "pro", "engineering military")],
    (1, 22): [("День таможенника", "pro", "border customs flag")],
    (1, 23): [("День ручного письма", "fun", "handwriting vintage pen letter")],
    (1, 24): [("Международный день образования", "international", "education books school")],
    (1, 25): [("День российского студенчества", "state", "students celebration books")],
    (1, 26): [("Международный день таможенника", "pro", "customs border flag")],
    (1, 27): [("День снятия блокады Ленинграда", "state", "memorial flame eternal flag"), ("Международный день памяти жертв Холокоста", "international", "memorial candles peace")],
    (1, 28): [("Международный день ёжика", "fun", "hedgehog cute animal")],
    (1, 29): [("День мобилизации против угрозы ядерной войны", "international", "peace doves white")],
    (1, 30): [("День деда Мороза и Снегурочки", "fun", "santa winter snow cozy")],
    (1, 31): [("День рождения Деда Мороза", "fun", "santa winter snow gift")],

    # ───────────────── ФЕВРАЛЬ ─────────────────
    (2, 1):  [("День экономиста", "pro", "finance economy office")],
    (2, 2):  [("День сурка", "fun", "groundhog winter snow"), ("День разгрома советскими войсками немецко-фашистских войск в Сталинградской битве", "state", "memorial flame flag")],
    (2, 3):  [("День борьбы с ненормативной лексикой", "fun", "books language clean")],
    (2, 4):  [("Всемирный день борьбы против рака", "international", "ribbon health awareness")],
    (2, 5):  [("День водопроводчика", "fun", "plumbing tools workshop")],
    (2, 6):  [("День бухгалтерского работника", "pro", "office calculator finance")],
    (2, 7):  [("День зимних видов спорта в России", "fun", "winter sport snow skiing")],
    (2, 8):  [("День российской науки", "pro", "science laboratory books")],
    (2, 9):  [("Международный день стоматолога", "pro", "dental health smile")],
    (2, 10): [("День памяти Пушкина", "fun", "books literature vintage pen")],
    (2, 11): [("Всемирный день больного", "international", "health hospital care")],
    (2, 12): [("День Дарвина", "fun", "science nature evolution")],
    (2, 13): [("Всемирный день радио", "international", "radio music vintage")],
    (2, 14): [("День святого Валентина", "fun", "love hearts roses romantic")],
    (2, 15): [("День памяти воинов-интернационалистов", "state", "memorial flame flag")],
    (2, 16): [("День неисправностей", "fun", "broken funny colorful")],
    (2, 17): [("День спонтанного проявления доброты", "fun", "kindness helping hands")],
    (2, 18): [("День транспортной полиции", "pro", "police law order")],
    (2, 19): [("Всемирный день социальной справедливости", "international", "justice equality hands")],
    (2, 20): [("Всемирный день социальной справедливости", "international", "justice peace hands")],
    (2, 21): [("Международный день родного языка", "international", "books language culture")],
    (2, 22): [("День апельсина", "fun", "orange citrus fruit colorful")],
    (2, 23): [("День защитника Отечества", "state", "patriotic blue sky nature flag")],
    (2, 24): [("День компьютерщика", "fun", "computer technology desk")],
    (2, 25): [("День экономии электроэнергии", "fun", "energy light bulb green")],
    (2, 26): [("День рассказывания историй у костра", "fun", "campfire night stars cozy")],
    (2, 27): [("День Сил специальных операций", "pro", "military flag honor")],
    (2, 28): [("Международный день редких заболеваний", "international", "health ribbon awareness")],
    (2, 29): [("День високосного года", "fun", "calendar time special")],

    # ───────────────── МАРТ ─────────────────
    (3, 1):  [("Всемирный день кошек", "fun", "cute cat kitten")],
    (3, 2):  [("День образования Чувашской автономной области", "state", "nature landscape"), ("День сурка по-русски", "fun", "groundhog cute snow")],
    (3, 3):  [("Всемирный день дикой природы", "international", "wildlife nature animals")],
    (3, 4):  [("День экспедитора", "pro", "logistics transport delivery")],
    (3, 5):  [("День неделания (Doing nothing day)", "fun", "relax cozy lazy comfortable")],
    (3, 6):  [("Международный день зубного врача", "pro", "dental smile health")],
    (3, 7):  [("День работника уголовно-исполнительной системы", "pro", "law order justice")],
    (3, 8):  [("Международный женский день", "state", "spring flowers women tulips")],
    (3, 9):  [("День Архива Уголовно-исполнительной системы", "fun", "books vintage history")],
    (3, 10): [("День архивов в России", "pro", "books vintage history archive")],
    (3, 11): [("День работников геодезии и картографии", "pro", "map geography travel")],
    (3, 12): [("День работников уголовно-исполнительной системы", "pro", "law order justice")],
    (3, 13): [("День экспериментального самолётостроения", "fun", "airplane sky aviation")],
    (3, 14): [("Международный день числа Пи", "international", "math science numbers")],
    (3, 15): [("Всемирный день защиты прав потребителей", "international", "shopping rights consumer")],
    (3, 16): [("День Реальных дел", "fun", "action motivation bright")],
    (3, 17): [("День Святого Патрика", "fun", "irish green clover celebration")],
    (3, 18): [("День принятия Крыма в состав России", "state", "crimea sea flag")],
    (3, 19): [("День моряка-подводника", "pro", "submarine navy ocean")],
    (3, 20): [("Международный день счастья", "international", "happiness joy sunshine")],
    (3, 21): [("Всемирный день поэзии", "international", "poetry books vintage")],
    (3, 22): [("Всемирный день воды", "international", "water ocean drop blue")],
    (3, 23): [("Всемирный день метеоролога", "pro", "weather sky clouds")],
    (3, 24): [("Всемирный день борьбы с туберкулёзом", "international", "health ribbon awareness")],
    (3, 25): [("День работника культуры", "pro", "culture art theater")],
    (3, 26): [("День специалиста юридической службы", "pro", "law justice building")],
    (3, 27): [("Международный день театра", "pro", "theater stage curtains")],
    (3, 28): [("День весеннего равноденствия (около этой даты)", "fun", "spring equinox flowers sunshine")],
    (3, 29): [("День специалиста по борьбе с экономическими преступлениями", "pro", "finance law office")],
    (3, 30): [("День защиты Земли", "fun", "earth planet green nature")],
    (3, 31): [("День патологоанатома", "pro", "science medical health")],
}
