# -*- coding: utf-8 -*-
HOLIDAYS_Q4 = {
    # ───────────────── ОКТЯБРЬ ─────────────────
    (10, 1):  [("Международный день музыки", "international", "music instruments concert"), ("Международный день пожилых людей", "international", "elderly family warmth tea")],
    (10, 2):  [("День профтехобразования", "pro", "education school books")],
    (10, 3):  [("Международный день architects", "international", "architecture building design")],
    (10, 4):  [("Всемирный день животных", "international", "animals cute pets nature")],
    (10, 5):  [("День учителя", "pro", "teacher school classroom books")],
    (10, 6):  [("День российского судьи", "pro", "law justice building")],
    (10, 7):  [("Всемирный день улыбки", "fun", "smile happy joy bright")],
    (10, 8):  [("День командира", "pro", "military flag honor")],
    (10, 9):  [("Всемирный день почты", "international", "mail letters delivery")],
    (10, 10): [("Всемирный день психического здоровья", "international", "health wellness mind care")],
    (10, 11): [("Международный день девочек", "international", "girls children colorful")],
    (10, 12): [("День кадрового работника", "pro", "office business people")],
    (10, 13): [("Международный день по снижению рисков катастроф", "international", "safety care awareness")],
    (10, 14): [("Покров Пресвятой Богородицы", "church", "orthodox church autumn candles")],
    (10, 15): [("Всемирный день сельских женщин", "international", "farm nature countryside")],
    (10, 16): [("Всемирный день хлеба", "international", "bread bakery warm rustic")],
    (10, 17): [("Международный день борьбы за ликвидацию нищеты", "international", "helping hands care")],
    (10, 18): [("День работников пищевой промышленности", "pro", "food industry kitchen")],
    (10, 19): [("День работников дорожного хозяйства", "pro", "road construction travel")],
    (10, 20): [("День военного связиста", "pro", "communication military")],
    (10, 21): [("День работников пищевой промышленности (рег.)", "pro", "food kitchen industry")],
    (10, 22): [("Праздник Белых журавлей", "fun", "birds sky nature memorial")],
    (10, 23): [("День работников рекламы", "pro", "marketing creative design")],
    (10, 24): [("День подразделений специального назначения", "pro", "military flag honor")],
    (10, 25): [("День таможенника (рег.)", "pro", "customs border flag")],
    (10, 26): [("День спортивного журналиста", "pro", "sport journalism camera")],
    (10, 27): [("День автомобилиста (альт.)", "pro", "car road travel")],
    (10, 28): [("День бабушек и дедушек", "fun", "grandparents family warmth")],
    (10, 29): [("День работников службы вневедомственной охраны", "pro", "police law order")],
    (10, 30): [("День памяти жертв политических репрессий", "state", "memorial candles peace")],
    (10, 31): [("Halloween", "fun", "halloween pumpkin autumn orange")],

    # ───────────────── НОЯБРЬ ─────────────────
    (11, 1):  [("День судебного пристава", "pro", "law justice building")],
    (11, 2):  [("День судебного пристава (альт.)", "pro", "law justice")],
    (11, 3):  [("День ОМОНа", "pro", "police military honor")],
    (11, 4):  [("День народного единства", "state", "unity people together russia")],
    (11, 5):  [("День военного разведчика", "pro", "military flag honor")],
    (11, 6):  [("День судебного пристава (рег.)", "pro", "law justice")],
    (11, 7):  [("День Октябрьской революции (памятная дата)", "state", "history flag memorial")],
    (11, 8):  [("День памяти погибших при исполнении служебных обязанностей сотрудников ОВД", "state", "memorial candles flag")],
    (11, 9):  [("Международный день антифашизма", "international", "peace unity flag")],
    (11, 10): [("День сотрудника органов внутренних дел", "pro", "police law order")],
    (11, 11): [("Всемирный день шопинга", "fun", "shopping gifts colorful")],
    (11, 12): [("Синичкин день", "fun", "birds winter nature cute")],
    (11, 13): [("Всемирный день доброты", "international", "kindness helping hands")],
    (11, 14): [("Международный день логопеда", "pro", "speech communication education")],
    (11, 15): [("День образования вооружения и техники РХБЗ", "pro", "military technology")],
    (11, 16): [("Международный день толерантности", "international", "unity people peace")],
    (11, 17): [("Международный день студентов", "international", "students celebration books")],
    (11, 18): [("День ракетных войск и артиллерии", "pro", "military flag honor")],
    (11, 19): [("День работников стекольной промышленности", "pro", "glass craft industry")],
    (11, 20): [("Всемирный день промышленности", "pro", "factory industry technology")],
    (11, 21): [("Всемирный день приветствий", "international", "greetings friendly people")],
    (11, 22): [("День психолога", "pro", "psychology mind care office")],
    (11, 23): [("День экономиста (рег.)", "pro", "finance economy office")],
    (11, 24): [("День моржа (любителей зимнего плавания)", "fun", "winter swimming snow")],
    (11, 25): [("Международный день борьбы за ликвидацию насилия в отношении женщин", "international", "support care hands")],
    (11, 26): [("День оценщика", "pro", "office finance documents")],
    (11, 27): [("День матери в России", "state", "mother family love warmth flowers")],
    (11, 28): [("День буквы Ё", "fun", "books russian language letters")],
    (11, 29): [("Международный день солидарности с палестинским народом", "international", "peace doves flag")],
    (11, 30): [("День домашних животных", "fun", "pets dog cat cute")],

    # ───────────────── ДЕКАБРЬ ─────────────────
    (12, 1):  [("Всемирный день борьбы со СПИДом", "international", "ribbon health awareness")],
    (12, 2):  [("День банковского работника", "pro", "finance office bank")],
    (12, 3):  [("День неизвестного солдата", "state", "memorial flame eternal flag"), ("Международный день инвалидов", "international", "support care hands")],
    (12, 4):  [("День заказов подарков Деду Морозу", "fun", "santa winter snow gift")],
    (12, 5):  [("День добровольца (волонтёра) в России", "state", "volunteer kindness helping hands")],
    (12, 6):  [("День Александра Невского", "church", "orthodox cross history flag")],
    (12, 7):  [("День образования российской таможни (альт.)", "pro", "customs border flag")],
    (12, 8):  [("День образования российской таможни", "pro", "customs border flag")],
    (12, 9):  [("День героев Отечества", "state", "memorial flag honor")],
    (12, 10): [("День прав человека", "international", "peace justice hands")],
    (12, 11): [("Международный день гор", "international", "mountains nature snow")],
    (12, 12): [("День Конституции России", "state", "russia flag government building")],
    (12, 13): [("День медиков-бактериологов", "pro", "science laboratory health")],
    (12, 14): [("День образования службы связи МВД", "pro", "communication police")],
    (12, 15): [("День образования российской таможни (рег.)", "pro", "customs border")],
    (12, 16): [("День Сухопутных войск", "pro", "military flag honor")],
    (12, 17): [("День ракетных войск стратегического назначения", "pro", "military flag honor")],
    (12, 18): [("Международный день мигранта", "international", "travel suitcase journey")],
    (12, 19): [("Никола Зимний", "church", "winter snow orthodox church candles")],
    (12, 20): [("День работника органов безопасности", "pro", "security law flag")],
    (12, 21): [("День зимнего солнцестояния", "fun", "winter solstice snow night")],
    (12, 22): [("День энергетика", "pro", "energy electricity industry")],
    (12, 23): [("День дальней авиации", "pro", "aviation military sky")],
    (12, 24): [("День взятия Измаила", "state", "memorial flag history")],
    (12, 25): [("Католическое Рождество", "fun", "christmas tree lights gifts cozy")],
    (12, 26): [("День сурдопереводчика", "pro", "communication hands care")],
    (12, 27): [("День спасателя", "pro", "rescue safety helping hands")],
    (12, 28): [("Международный день кино", "international", "cinema film movie theater")],
    (12, 29): [("День заказа новогодних подарков", "fun", "gift winter snow celebration")],
    (12, 30): [("День заключения договора об образовании СССР (памятная дата)", "state", "history flag memorial")],
    (12, 31): [("Канун Нового года", "state", "new year eve fireworks champagne")],
}
