# -*- coding: utf-8 -*-
HOLIDAYS_Q2 = {
    # ───────────────── АПРЕЛЬ ─────────────────
    (4, 1):  [("День смеха", "fun", "funny cheerful colorful balloons")],
    (4, 2):  [("Международный день детской книги", "international", "children books colorful")],
    (4, 3):  [("Всемирный день поэтической мысли", "fun", "poetry books vintage")],
    (4, 4):  [("Международный день мин", "international", "peace safety")],
    (4, 5):  [("День мецената и благотворителя", "fun", "charity helping hands kindness")],
    (4, 6):  [("День российской анимации", "fun", "animation cartoon colorful")],
    (4, 7):  [("Всемирный день здоровья", "international", "health wellness nature")],
    (4, 8):  [("Международный день цыган", "international", "culture tradition colorful")],
    (4, 9):  [("День войск противовоздушной обороны", "pro", "military aviation sky")],
    (4, 10): [("День войск противовоздушной обороны", "pro", "aviation military sky")],
    (4, 11): [("Международный день освобождения узников фашистских концлагерей", "international", "memorial peace candles")],
    (4, 12): [("День космонавтики", "state", "space stars cosmos rocket")],
    (4, 13): [("Всемирный день рок-н-ролла", "fun", "music guitar concert")],
    (4, 14): [("День Республики Крым", "state", "crimea sea flag")],
    (4, 15): [("День экологических знаний", "fun", "nature green earth forest")],
    (4, 16): [("День щедрости", "fun", "kindness helping hands gift")],
    (4, 17): [("День российской науки (карты, геодезисты)", "pro", "science map books")],
    (4, 18): [("Международный день памятников и исторических мест", "international", "history architecture culture")],
    (4, 19): [("День подснежника", "fun", "snowdrop flower spring")],
    (4, 20): [("Национальный день донора в России", "fun", "donation health hands kind")],
    (4, 21): [("День местного самоуправления", "state", "city government building")],
    (4, 22): [("Международный день Земли", "international", "earth planet nature green")],
    (4, 23): [("Всемирный день книг", "international", "books reading library")],
    (4, 24): [("Международный день солидарности молодёжи", "international", "youth celebration colorful")],
    (4, 25): [("Международный день породненных городов", "international", "city architecture friendship")],
    (4, 26): [("День российской полиграфии", "pro", "printing books paper")],
    (4, 27): [("День российского парламентаризма", "state", "government building flag")],
    (4, 28): [("Всемирный день охраны труда", "international", "safety work office")],
    (4, 29): [("Международный день танца", "international", "dance art colorful")],
    (4, 30): [("День пожарной охраны", "pro", "fire safety red truck")],

    # ───────────────── МАЙ ─────────────────
    (5, 1):  [("Праздник Весны и Труда", "state", "spring flowers nature blooming")],
    (5, 2):  [("День велосипеда", "fun", "bicycle nature outdoor")],
    (5, 3):  [("Всемирный день свободы печати", "international", "newspaper press freedom")],
    (5, 4):  [("День сотрудников пожарной охраны", "pro", "fire safety red truck")],
    (5, 5):  [("День водолаза", "pro", "ocean diving underwater")],
    (5, 6):  [("День Георгия Победоносца", "church", "orthodox cross history")],
    (5, 7):  [("День радио", "pro", "radio vintage music")],
    (5, 8):  [("Международный день Красного Креста", "international", "health helping hands care")],
    (5, 9):  [("День Победы", "state", "red carnations memorial flame eternal")],
    (5, 10): [("День Чёрного моря", "fun", "sea ocean blue coast")],
    (5, 11): [("День работников добывающей промышленности", "pro", "mining industry")],
    (5, 12): [("Международный день медицинской сестры", "pro", "nurse health hospital care")],
    (5, 13): [("День Черноморского флота", "pro", "navy ocean ship flag")],
    (5, 14): [("День фрилансера", "fun", "laptop work freedom coffee")],
    (5, 15): [("Международный день семьи", "international", "family togetherness home")],
    (5, 16): [("Международный день света", "international", "light sun bright")],
    (5, 17): [("Всемирный день электросвязи", "international", "communication technology")],
    (5, 18): [("Международный день музеев", "international", "museum art history")],
    (5, 19): [("День пионерии", "fun", "history vintage red")],
    (5, 20): [("Всемирный день метролога", "pro", "science measurement tools")],
    (5, 21): [("Всемирный день культурного разнообразия", "international", "culture diversity colorful")],
    (5, 22): [("Международный день биологического разнообразия", "international", "nature wildlife forest")],
    (5, 23): [("Всемирный день черепахи", "fun", "turtle cute animal")],
    (5, 24): [("День славянской письменности и культуры", "church", "books manuscripts orthodox")],
    (5, 25): [("День филолога", "fun", "books language literature")],
    (5, 26): [("День российского предпринимательства", "pro", "business office success")],
    (5, 27): [("Общероссийский день библиотек", "pro", "library books reading")],
    (5, 28): [("День пограничника", "pro", "border military flag")],
    (5, 29): [("Международный день миротворцев ООН", "international", "peace doves flag")],
    (5, 30): [("День ветеранов органов внутренних дел", "pro", "police law honor")],
    (5, 31): [("Всемирный день без табака", "international", "health clean fresh")],

    # ───────────────── ИЮНЬ ─────────────────
    (6, 1):  [("День защиты детей", "state", "children happy playground colorful")],
    (6, 2):  [("День здорового питания и отказа от излишеств в еде", "fun", "healthy food fruits vegetables")],
    (6, 3):  [("Всемирный день велосипеда", "international", "bicycle nature outdoor")],
    (6, 4):  [("Международный день невинных детей — жертв агрессии", "international", "peace children candles")],
    (6, 5):  [("Всемирный день окружающей среды", "international", "nature forest green environment")],
    (6, 6):  [("День русского языка (День Пушкина)", "fun", "books pushkin literature")],
    (6, 7):  [("День работников лёгкой промышленности", "pro", "textile fabric industry")],
    (6, 8):  [("Всемирный день океанов", "international", "ocean sea waves blue")],
    (6, 9):  [("Международный день друзей", "fun", "friends together happy")],
    (6, 10): [("День мороженого", "fun", "ice cream sweet summer")],
    (6, 11): [("День работников текстильной промышленности", "pro", "textile fabric industry")],
    (6, 12): [("День России", "state", "russia nature landscape flag")],
    (6, 13): [("Всемирный день переливания крови", "international", "health donation care")],
    (6, 14): [("Всемирный день донора крови", "international", "donation health hands")],
    (6, 15): [("Международный день ветра", "fun", "wind sky clouds nature")],
    (6, 16): [("День медицинского работника", "pro", "health hospital care doctor")],
    (6, 17): [("Всемирный день борьбы с опустыниванием", "international", "desert nature dry")],
    (6, 18): [("День автомобилиста", "pro", "car road travel")],
    (6, 19): [("День моряка-подводника", "pro", "submarine navy ocean")],
    (6, 20): [("Всемирный день беженцев", "international", "peace helping hands")],
    (6, 21): [("День летнего солнцестояния", "fun", "summer sun bright sky")],
    (6, 22): [("День памяти и скорби", "state", "memorial flame candle"), ("День шоколадного эклера", "fun", "dessert sweet pastry chocolate"), ("Всемирный день верблюда", "fun", "camel desert animal"), ("Всемирный день купания", "fun", "swimming pool summer water"), ("День народных художественных промыслов", "pro", "crafts handmade traditional")],
    (6, 23): [("Международный олимпийский день", "international", "sport olympics flag")],
    (6, 24): [("День молодёжи (в некоторых регионах)", "fun", "youth celebration colorful")],
    (6, 25): [("День моряка", "pro", "sailor navy ocean ship")],
    (6, 26): [("Международный день борьбы с наркоманией", "international", "health clean fresh")],
    (6, 27): [("День молодёжи", "fun", "youth celebration colorful")],
    (6, 28): [("День работников статистики", "pro", "data office charts")],
    (6, 29): [("День изобретателя и рационализатора", "fun", "invention creativity lightbulb")],
    (6, 30): [("День экономиста (региональный)", "pro", "finance economy office")],
}
